name: CI/CD using Github Actions

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build Application
        run: mvn clean package

      - name: Configure aws Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AK }}
          aws-secret-access-key: ${{ secrets.SAK }}
          aws-region: eu-north-1
          
      - name: Store artifact to s3
        run: aws s3 cp target/*.war s3://uma.online/student.war

      - name: Docker Build 
        run: | 
          docker build -t student . 
          docker images

      - name: Trivy Install 
        run: |
          sudo apt-get update
          sudo apt-get install -y wget 
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
            gpg --dearmor | \
            sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | \
            sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy
      
      - name: Scan image using Trivy
        run: trivy image --scanners vuln --severity HIGH,CRITICAL --exit-code 0 student:latest

      - name: Push image to ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 580222437000.dkr.ecr.eu-north-1.amazonaws.com
          docker tag student:latest 580222437000.dkr.ecr.eu-north-1.amazonaws.com/student:latest
          docker push 580222437000.dkr.ecr.eu-north-1.amazonaws.com/student:latest

      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v4

      - name: Terraform init
        run: terraform init

      - name: Terraform fmt 
        run: terraform fmt

      - name: Terraform validate
        run: terraform validate

      - name: Terraform apply 
        run: terraform apply -auto-approve

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Configure EKS cluster 
        run: aws eks update-kubeconfig --name my-eks-cluster --region eu-north-1
          
      - name: Deployment On kubernetes
        run: |
          kubectl apply -f k8s/
          sleep 30
          kubectl get pods 
          kubectl get svc -o wide
